export default {
  products: [
    {
      _id : '1',
      name: "Bengkirai",
      category: "kayu",
      image: "/images/jd.jpg",
      price: 200000,
      brand: " kayu",
      rating: 4.5,
      numReviews: 10,
    },
    {
      _id : '2',
      name: "Galam",
      category: "kayu",
      image: "/images/jd.jpg",
      price: 150000,
      brand: " kayu",
      rating: 4.0,
      numReviews: 10,
    },
    {
      _id : '3',
      name: "Meranti",
      category: "kayu",
      image: "/images/jd.jpg",
      price: 250000,
      brand: " kayu",
      rating: 4.9,
      numReviews: 10,
    },
    {
      _id : '4',
      name: "Meranti",
      category: "kayu",
      image: "/images/jd.jpg",
      price: 250000,
      brand: " kayu",
      rating: 4.9,
      numReviews: 10,
    },
    {
      _id : '5',
      name: "Meranti",
      category: "kayu",
      image: "/images/jd.jpg",
      price: 250000,
      brand: " kayu",
      rating: 4.9,
      numReviews: 10,
    },
  ]
};
